# Spring Properties
spring:
  application:
    name: consumer
  profiles:
    active: local

  # Database Configuration (PostgreSQL)
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shorthand_db}
    username: ${DB_USERNAME:shorthand_user}
    password: ${DB_PASSWORD:shorthand_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: analytics
    schemas: analytics

  # Message Queue Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: shorthand-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Server Configuration
server:
  port: 8081